/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.pixArt.View;


import javafx.application.Application;

/** Main application entry-point's class. */

public final class App {
    
}